/************************************************/
/*	Author		:		Mohamed G. ELeish		*/
/*	Date		:		5 September 2021		*/
/*	Version		:		V01						*/
/************************************************/

/************************************************/
/************************************************/
/*****					LOG					*****/
/*	5/9/2021:	File Created					*/
/************************************************/
/************************************************/
#ifndef NVIC_INTERFACE_H_INCLUDED
#define NVIC_INTERFACE_H_INCLUDED

typedef enum{
	NVIC_INTERRUPT_WWDG,
	NVIC_INTERRUPT_PVD,
	NVIC_INTERRUPT_TAMPER,
	NVIC_INTERRUPT_RTC,
	NVIC_INTERRUPT_FLASH,
	NVIC_INTERRUPT_RCC,
	NVIC_INTERRUPT_EXTI0,
	NVIC_INTERRUPT_EXTI1,
	NVIC_INTERRUPT_EXTI2,
	NVIC_INTERRUPT_EXTI3,
	NVIC_INTERRUPT_EXTI4,
	NVIC_INTERRUPT_DMA1_CH1,
	NVIC_INTERRUPT_DMA1_CH2,
	NVIC_INTERRUPT_DMA1_CH3,
	NVIC_INTERRUPT_DMA1_CH4,
	NVIC_INTERRUPT_DMA1_CH5,
	NVIC_INTERRUPT_DMA1_CH6,
	NVIC_INTERRUPT_DMA1_CH7,
	NVIC_INTERRUPT_ADC_1_2,
	NVIC_INTERRUPT_USB_HP_CAN_TX,
	NVIC_INTERRUPT_USB_LP_CAN_RX0,
	NVIC_INTERRUPT_CAN_RX1,
	NVIC_INTERRUPT_CAN_SCE,
	NVIC_INTERRUPT_EXTI5_9,
	NVIC_INTERRUPT_TIM1_BRK,
	NVIC_INTERRUPT_TIM1_UP,
	NVIC_INTERRUPT_TIM1_TRG_COM,
	NVIC_INTERRUPT_CC,
	NVIC_INTERRUPT_TIM2,
	NVIC_INTERRUPT_TIM3,
	NVIC_INTERRUPT_TIM4,
	NVIC_INTERRUPT_I2C1_EV,
	NVIC_INTERRUPT_I2C1_ER,
	NVIC_INTERRUPT_I2C2_EV,
	NVIC_INTERRUPT_I2C2_ER,
	NVIC_INTERRUPT_SPI1,
	NVIC_INTERRUPT_SPI2,
	NVIC_INTERRUPT_USART1,
	NVIC_INTERRUPT_USART2,
	NVIC_INTERRUPT_USART3,
	NVIC_INTERRUPT_EXTI10_15,
	NVIC_INTERRUPT_RTCALARM,
	NVIC_INTERRUPT_USBWAKEUP,
	NVIC_INTERRUPT_TIM8_BRK,
	NVIC_INTERRUPT_TIM8_UP,
	NVIC_INTERRUPT_TIM8_TRG_COM,
	NVIC_INTERRUPT_TIM8_CC,
	NVIC_INTERRUPT_ADC3,
	NVIC_INTERRUPT_FSMC,
	NVIC_INTERRUPT_SDIO,
	NVIC_INTERRUPT_TIM5,
	NVIC_INTERRUPT_SPI3,
	NVIC_INTERRUPT_USART4,
	NVIC_INTERRUPT_USART5,
	NVIC_INTERRUPT_TIM6,
	NVIC_INTERRUPT_TIM7,
	NVIC_INTERRUPT_DMA2_CH1,
	NVIC_INTERRUPT_DMA2_CH2,
	NVIC_INTERRUPT_DMA2_CH3,
	NVIC_INTERRUPT_DMA2_CH4_5
}NVIC_InterruptID_t;

typedef enum{
	NVIC_GROUP_1,
	NVIC_GROUP_2,
	NVIC_GROUP_3,
	NVIC_GROUP_4,
	NVIC_GROUP_5,
	NVIC_GROUP_6,
	NVIC_GROUP_7,
	NVIC_GROUP_8,
	NVIC_GROUP_9,
	NVIC_GROUP_10,
	NVIC_GROUP_11,
	NVIC_GROUP_12,
	NVIC_GROUP_13,
	NVIC_GROUP_14,
	NVIC_GROUP_15,
	NVIC_GROUP_16,
}NVIC_GroupPriority_t;

typedef enum{
	NVIC_SUB_1,
	NVIC_SUB_2,
	NVIC_SUB_3,
	NVIC_SUB_4,
	NVIC_SUB_5,
	NVIC_SUB_6,
	NVIC_SUB_7,
	NVIC_SUB_8,
	NVIC_SUB_9,
	NVIC_SUB_10,
	NVIC_SUB_11,
	NVIC_SUB_12,
	NVIC_SUB_13,
	NVIC_SUB_14,
	NVIC_SUB_15,
	NVIC_SUB_16,
}NVIC_SubPriority_t;

typedef enum{
	NVIC_CONFIG_16_GROUP_1_SUB,
	NVIC_CONFIG_8_GROUP_2_SUB,
	NVIC_CONFIG_4_GROUP_4_SUB,
	NVIC_CONFIG_2_GROUP_8_SUB,
	NVIC_CONFIG_1_GROUP_16_SUB
}NVIC_Config_t;

void MNVIC_voidEnableInterrupt(NVIC_InterruptID_t Interrupt);

void MNVIC_voidDisableInterrupt(NVIC_InterruptID_t Interrupt);

void MNVIC_voidSetPendingFlag(NVIC_InterruptID_t Interrupt);

void MNVIC_voidClearPendingFlag(NVIC_InterruptID_t Interrupt);

u8 MNVIC_u8GetPendingFlag(NVIC_InterruptID_t Interrupt);

u8 MNVIC_u8GetActiveFlag(NVIC_InterruptID_t Interrupt);

void MNVIC_voidSetInterruptPriority(NVIC_InterruptID_t Interrupt, NVIC_GroupPriority_t Group, NVIC_SubPriority_t Sub );

void MNVIC_voidInit(NVIC_Config_t Config);

#endif

